language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.7-dev"  # 3.7 development branch
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build
# command to install dependencies
install:
  - pip install '.[dev]'
script:
  - pytest

after_success:
  python ./setup.py sdist
  twine upload -u "$PYPI_USER" -p "$PYPI_PASSWORD" --skip-existing dist/*

# deploy:
#   provider: pypi
#   user: "$PYPI_USER"
#   password: "$PYPI_PASSWORD"
#   # on:
#   #   tags: true
